on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      already_published: ${{ steps.npm_check.outputs.already_published }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - id: npm_check
        run: |
          NAME=$(node -p "require('./package.json').name")
          VERSION=$(node -p "require('./package.json').version")

          if npm view "$NAME@$VERSION" version >/dev/null 2>&1; then
            echo "already_published=true" >> $GITHUB_OUTPUT
          else
            echo "already_published=false" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: check-version
    if: needs.check-version.outputs.already_published != 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org

      - name: Check for Rust Code
        id: check_rust
        run: |
          if [ -f "Cargo.toml" ]; then
            echo "has_rust=true" >> $GITHUB_OUTPUT
          else
            echo "has_rust=false" >> $GITHUB_OUTPUT
          fi

      - name: Install Rust (WASM Target)
        if: steps.check_rust.outputs.has_rust == 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: |
          bun pm pack
          npm publish *.tgz
